export const BRAND_TYPES = {
  EXPAND_MAIN_MENU: "EXPAND_MAIN_MENU",
  CHECK_MAIN_MENU: "CHECK_MAIN_MENU",
  CHECK_SUB_MENU: "CHECK_SUB_MENU",
  CHECK_MAIN_CITY: "CHECK_MAIN_CITY",
  CHECK_SUB_CITY: "CHECK_SUB_CITY",
};
