import product from "../../assets/images/section/activity_image.jpg"; // with import

export const PRODUCTS = [
  {
    id: "u1",
    name: "Beira Group is the largest brush manufacturer ",
    image: product,
    discount: "20%",
    rating: "4.6",
    pricestrike: "288",
    price: "200",
    description: "duriyantree.com is an ecommerce site. ",
    views: "255",
  },
  {
    id: "u1",
    name: "Beira Group is the largest brush manufacturer ",
    image: product,
    discount: "20%",
    rating: "4.6",
    pricestrike: "288",
    price: "200",
    description: "duriyantree.com is an ecommerce site. ",
    views: "255",
  },
  {
    id: "u1",
    name: "Beira Group is the largest brush manufacturer ",
    image: product,
    discount: "20%",
    rating: "4.6",
    pricestrike: "288",
    price: "200",
    description: "duriyantree.com is an ecommerce site. ",
    views: "255",
  },
  {
    id: "u1",
    name: "Beira Group is the largest brush manufacturer ",
    image: product,
    discount: "20%",
    rating: "4.6",
    pricestrike: "288",
    price: "200",
    description: "duriyantree.com is an ecommerce site. ",
    views: "255",
  },
  {
    id: "u1",
    name: "Beira Group is the largest brush manufacturer ",
    image: product,
    discount: "20%",
    rating: "4.6",
    pricestrike: "288",
    price: "200",
    description: "duriyantree.com is an ecommerce site. ",
    views: "255",
  },
];
